// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/Henryarrovin/auth-service/config"
	"github.com/Henryarrovin/auth-service/data"
	"github.com/Henryarrovin/auth-service/handlers"
	"github.com/Henryarrovin/auth-service/services/auth_service"
	"github.com/Henryarrovin/auth-service/services/email_service"
	"github.com/Henryarrovin/auth-service/services/jwt_service"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func InitializeContainer(cfgFile string, logger *zap.Logger) (*handlers.AuthHandler, func(), error) {
	configConfig, err := config.Load(cfgFile)
	if err != nil {
		return nil, nil, err
	}
	db, err := data.NewDB(configConfig, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepository := data.NewUserRepository(db)
	tokenStore, err := data.NewTokenStore(configConfig)
	if err != nil {
		return nil, nil, err
	}
	jwtConfig := config.ProvideJWTConfig(configConfig)
	jwtService := jwt_service.NewJWTService(jwtConfig)
	emailConfig := config.ProvideEmailConfig(configConfig)
	emailService := email_service.NewEmailService(emailConfig, logger)
	authService := auth_service.NewAuthService(userRepository, tokenStore, jwtService, emailService, logger)
	authHandler := handlers.NewAuthHandler(authService, logger)
	return authHandler, func() {
	}, nil
}

// wire.go:

func buildLogger(env string) (*zap.Logger, error) {
	var cfg zap.Config
	if env == "production" {
		cfg = zap.NewProductionConfig()
	} else {
		cfg = zap.NewDevelopmentConfig()
	}

	cfg.EncoderConfig.CallerKey = "caller"
	cfg.Development = true

	return cfg.Build(zap.AddCaller(), zap.AddCallerSkip(0))
}
